version: '3.8'

services:
  geowifi-api:
    build: .
    container_name: geowifi-api
    ports:
      - "8000:8000"
    volumes:
      - ./gw_utils:/app/gw_utils  # 挂载配置文件目录
      - ./results:/app/results    # 挂载结果目录
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai         # 设置时区
      - HOST=0.0.0.0            # uvicorn 主机地址
      - PORT=8000               # uvicorn 端口
      - WORKERS=4               # uvicorn 工作进程数
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 20s
      timeout: 3s
      retries: 2
      start_period: 60s